try {
    let x = 2;
}
catch (e) {
    console.log(e);
}
finally {
    console.log("done");
}